ALTER USER 'root' @'localhost' IDENTIFIED
WITH
    mysql_native_password BY 'root';

CREATE DATABASE IF NOT EXISTS enboost;
USE enboost;

CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS translated_words (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    wordEnglish VARCHAR(100) NOT NULL,
    wordPortuguese VARCHAR(100) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_user INTEGER,
    FOREIGN KEY (id_user) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS remember_words (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    wordEnglish VARCHAR(100) NOT NULL,
    wordPortuguese VARCHAR(100) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_user INTEGER,
    FOREIGN KEY (id_user) REFERENCES users (id) ON DELETE SET NULL
);

